trigger:
  branches:
    include:
      - main

pool:
  name: Default
  demands:
    - Agent.OS -equals Windows_NT

steps:
# Step 1: Install Node.js
- task: UseNode@1
  inputs:
    version: '16.x'
    checkLatest: true

# Step 2: Install dependencies
- script: |
    npm install
  displayName: 'Install Dependencies'

# Step 3: Build the project
- script: |
    npm run build
  displayName: 'Build Project'

# Step 4: Publish build artifacts (Optional)
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: './dist'
    artifactName: 'vite-react-app'
  displayName: 'Publish Build Artifacts'
